### ISSUE TITLE
Update Usage Docs

### ISSUE THREAD

**Issue by garomonegro** [keikoproj/kubedog#32]
Update docs with:

- [x] How to use #23 
- [x] The new steps of #26 
- [x] Steps syntax flexibility add in #39
